### ISSUE TITLE
QR kod, krótki lnk na spotkanie

### ISSUE THREAD

**Issue by kpodsiad** [JanTry/IO_TEAM_B_20-21#11]
Jako student mogę dołączyć do spotkania (QR kod, krótki link) by nie tracić czasu

**Comment by szarbartosz** [comment]
kryteria akceptacji:
- [ ] wygenerowanie krótkiego linku pozwalającego na bezpośrednie przejście do spokania
- [ ] student po kliknięciu w link i zalogowaniu jest od razu przenoszony do spotkania udostępnionego przez wykładowcę
