### ISSUE TITLE
Predefiniowane reakcje dla studenta

### ISSUE THREAD

**Issue by kpodsiad** [JanTry/IO_TEAM_B_20-21#16]
Jako student chciałbym mieć możliwość użycia jednej z dostępnych reakcji aby zasygnalizowac swój status w danym momencie (łapka w górę)

**Comment by szarbartosz** [comment]
kryteria akceptacji:
- [ ] możliwość użycia jednej z predefiniowanych reakcji przez studenta
- [ ] wyświetlenie informacji o użyciu reakcji przez studenta na koncie wykładowcy (np. wyświetlenie 5 sekundowego powiadomienia w formie <studentname>: <reaction>)
