### ISSUE TITLE
Statystyki quizu dla studenta (po zakończeniu)

### ISSUE THREAD

**Issue by kpodsiad** [JanTry/IO_TEAM_B_20-21#18]
Jako student chciałbym zobaczyć liczbę punktów zdobytych za dany quiz (o ile był punktowany) aby wiedzieć jak mi poszło

**Comment by szarbartosz** [comment]
kryteria akceptacji:
- [ ] wyświetlenie liczb zdoytych punktów po zakończonym quizie
