### ISSUE TITLE
Statystyki danego quizu

### ISSUE THREAD

**Issue by kpodsiad** [JanTry/IO_TEAM_B_20-21#21]
Jako nauczyciel chciałbym mieć wgląd do statystyk quizu (rozkład punktów w poszczególnych pytaniach)

**Comment by szarbartosz** [comment]
kryteria akceptacji:
- [ ] wyświetlenie liczby poprawnych i niepoprawnych odpowiedzi na wszystkie pytania w zadanym quizie
